swagger: '2.0'

info:
  version: 0.1.0
  title: AS Template Flask API
  description: 'Template flask padr√£o APIs REST..'
  contact:
    email: patrick@ibm.com

schemes:
  - http

tags:
  - name: AS Template
    description: 'Welcome to AS Template Flask API.'

paths:
  /main:
    post:
      tags:
        - AS Template
      description: 'AS Template Flask API.'
      parameters:
        - name: main
          in: body
          required: true
          description: 'teste'
          schema:
            $ref: '#/definitions/main'
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/Response200'

definitions:
  main:
    type: object
    properties:
    example: {
      "textoMensagem": "As"
    }